# Generated by Django 3.2.16 on 2023-01-15 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alt_text',
            field=models.TextField(default='alt', max_length=125),
            preserve_default=False,
        ),
    ]
