# Generated by Django 3.2.16 on 2023-01-15 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0006_project_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dexterity_level',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_3D_printer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instruction_level',
            field=models.IntegerField(null=True),
        ),
    ]
