# Generated by Django 4.1.6 on 2023-02-08 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0004_requirements_dexterity_requirements_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='requirements',
        ),
        migrations.AddField(
            model_name='requirements',
            name='tools',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='making.tool'),
            preserve_default=False,
        ),
    ]
