# Generated by Django 4.1.6 on 2023-02-08 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0006_remove_requirements_tools_tool_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='requirements',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='making.requirements'),
            preserve_default=False,
        ),
    ]
