# Generated by Django 4.1.6 on 2023-02-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0008_project_description_project_instructions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='requirements',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='making.requirements'),
        ),
    ]
