# Generated by Django 4.1.6 on 2023-02-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0009_alter_userprofile_requirements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='profile_name',
        ),
    ]
