# Generated by Django 4.1.6 on 2023-03-14 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0011_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='requirements',
            options={'verbose_name': 'Requirements', 'verbose_name_plural': 'Requirements'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
    ]
