# Generated by Django 4.1.6 on 2023-03-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0013_project_materials'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tool',
            constraint=models.UniqueConstraint(fields=('name', 'requirements'), name='unique_tool'),
        ),
    ]
