# Generated by Django 4.1.6 on 2023-02-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=1)),
            ],
        ),
    ]
