# Generated by Django 4.1.6 on 2023-02-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0002_project_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='making.requirements'),
        ),
    ]
