# Generated by Django 4.1.6 on 2023-03-14 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0010_rename_user_name_userprofile_profile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
    ]
