# Generated by Django 4.1.6 on 2023-03-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0012_alter_project_options_alter_requirements_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='materials',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
