# Generated by Django 4.1.6 on 2023-03-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('making', '0015_alter_project_materials_alter_requirements_dexterity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='dexterity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text="This is how much you can use your hands to do things.<ul class='list-unstyled'><li> Low: you can put Duplo blocks together. </li><li>Medium: you can </li><li>High: you can put Lego blocks together. </li> </ul>"),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='language',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text="This is what sort of instructions you can understand.<ul class='list-unstyled'><li> Low: you can </li><li>Medium: you can </li><li>High: you can </li> </ul>"),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='memory',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text="This is what your memory is like.<ul class='list-unstyled'><li> Low: you can </li><li>Medium: you can </li><li>High: you can </li> </ul>"),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='vision',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1, help_text="This is how much you can see. <ul class='list-unstyled'><li> Low: you can read off a road sign.</li><li>Medium: you can read large text.</li><li>High: you can read small text.</li> </ul>"),
        ),
        migrations.AlterField(
            model_name='tool',
            name='skill_level',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Beginner'), (2, 'Competent'), (3, 'Expert')], default=0),
        ),
    ]
